# Generated by Django 5.0.2 on 2024-02-07 15:44

from django.db import migrations
import uuid


def create_sample_data(apps, schema_editor):
    for _ in range(10):
        CreditOrder = apps.get_model('creditapp', 'CreditOrder')
        Contract = apps.get_model('creditapp', 'Contract')
        Vendor = apps.get_model('creditapp', 'Vendor')
        Product = apps.get_model('creditapp', 'Product')

        credit_order = CreditOrder.objects.create(name=f'CreditOrder_{str(uuid.uuid4())}')

        contract = Contract.objects.create(name=f'Contract_{str(uuid.uuid4())}', credit_order=credit_order)

        vendor = Vendor.objects.create(name=f'Vendor_{str(uuid.uuid4())}')

        product = Product.objects.create(
            name=f'Product_{str(uuid.uuid4())}',
            credit_order=credit_order,
            vendor=vendor
        )

class Migration(migrations.Migration):

    dependencies = [
        ('creditapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_sample_data),
    ]
